version: '3'

services:

  web:
    build: .
    container_name: web_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/celery_app
    ports:
      - "8000:8000"
    depends_on:
      - my_cache
    restart: always
    networks:
      - anupam      

  my_cache:
    image: redis:latest
    container_name: my_cache
    # restart: always
    # command: redis-server --save 20 1 --loglevel warning
    expose:
      - 6379
    networks:
      - anupam    

  celery_beat:
    build: .
    container_name: my_celery_beat
    command: celery -A celery_p beat -l info
    volumes:
      - .:/celery_app
    depends_on:
      - my_cache
      - web
    networks:
      - anupam      


  celery_api:
    build: .
    container_name: my_celery_worker
    command: celery -A celery_p worker -l info -c 4
    volumes:
      - .:/celery_app
    depends_on:
      - my_cache
      - web
    networks:
      - anupam

networks:
  anupam:
    driver: bridge

